### ISSUE TITLE
Problème OCX.

### ISSUE THREAD

**Issue by Supportremi** [CEREMA/territoires-ville.StructUrb#1]
Bonjour, 

L'application n'est pas utilisable après le lancement : 
Lancement avec l'utilisateur admin de sa machine : Erreur d'exécution richtx32.ocx
Lancement en mode administrateur : Le composant COMDLG32.OCX n'est pas enregistré....

Une astuce ? un pack VB6 à installer ?

Merci d'avance

**Comment by Luudoo** [comment]
Bonjour,

Certaines librairies et composants nécessaires ne sont pas livrés avec le code source, n'étant pas forcément libres, ni propriété du CEREMA.
Il n'est pas possible de faire fonctionner ces logiciels directement en téléchargeant ces sources et l'exécutable principal.
Il est par contre possible, en récupérant les fichiers manquant si cela est permis, de faire fonctionner ces logiciels, et éventuellement de rebâtir les projets Visual Basic permettant de les modifier (à condition bien entendu de disposer de l'environnement de développement Visual Basic 6)
Cf https://www.cerema.fr/fr/centre-ressources/boutique/logiciels-territoires-ville

**Comment by Supportremi** [comment]
Bonjour, 

Pour information, l'installation du lien ci-dessous corrige le problème.

https://sourceforge.net/projects/vb6extendedruntime/

Cordialement, 

Rémi

**Comment by Luudoo** [comment]
Bonjour,

Il faut en effet le runtime VB6 puisque c'est une application VB6, mais il y a potentiellement d'autres composants manquants, que vous ne pourrez voir que lors de l'utilisation des fonctionnalités qui en ont besoin, ou lors de la compilation du projet VB6 si vous êtes en mesure de rebâtir un tel projet VB6...

Cordialement,

**Comment by danyro67** [comment]
Bonjour,
Ci-joint une nouvelle version avec setup et docu
[Struct-Urb_V2.2.0_codesource.zip](https://github.com/CEREMA/territoires-ville.StructUrb/files/13973113/Struct-Urb_V2.2.0_codesource.zip)
[Struct-Urb_V2.2.0_setup.zip](https://github.com/CEREMA/territoires-ville.StructUrb/files/13973114/Struct-Urb_V2.2.0_setup.zip)

Je veux bien le mettre sur github mais vous pouvez m'expliquer la marche à suivre ?

Daniel

**Comment by danyro67** [comment]
je me suis également permis d'enlever l'utilitaire de licence et repris la docu en format plus "neutre"

j'ai pu récupérer l'aide HTML par contre l'aide contextuelle ne fonctionne pas (pb d'index apparemment mais je ne trouve pas le pb)

autre point, le programme utilise le composant Spread Com pour l'affichage des infos avec plusieurs options
ça concerne l'affichage des caractéristiques des enrobés sur l'onglet "structure", j'imagine que ça présente les données sous forme de tableau
par contre c'est 1300 la licence et sans garantie que ça fonctionne sur vb6 
ça n'empêche pas le logiciel de tourner, on a accès aux caractéristiques sur l'onglet "couche de surface"
et je pense qu'on pourra faire autrement pour l'affichage sur l'onglet structure, c'est vraiment du détail

niveau évolution ça me semble un peu verrouillé : de ce que j'ai compris on a les matériaux dans le fichier .mts et des solutions types dans le fichier .str mais elles ont dû être calculées sur Alizé, donc je ne vois pas comment enrichir la base
éventuellement au niveau de l'esthétique (ça fait très windows xp)
niveau ergonomie je trouve ça très bien, on perd pas de temps pour la saisie
